name: weibo-trending-hot-search

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: Kesin11/actions-timeline@v1
        with:
         github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run
        env:
          ENDPOINT_URL: ${{ secrets.ENDPOINT_URL }}
          IMG_ACCESS_URL: ${{ secrets.IMG_ACCESS_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        run: python3 main.py
      - name: Commit files
        run: |
          git config --local user.email "sxyx2008@163.com"
          git config --local user.name "冯靖"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -m "update by github action"
          git push
